const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.LocalStorage,
		C3.Plugins.Photon,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Photon.Acts.connect,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Photon.Acts.createRoom,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Photon.Acts.requestLobbyStats,
		C3.Plugins.Photon.Acts.joinRoom,
		C3.Plugins.Photon.Exps.RoomNameAt,
		C3.Plugins.Photon.Cnds.onLobbyStats,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Photon.Exps.RoomCount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Photon.Exps.RoomIsOpen,
		C3.Plugins.Photon.Exps.RoomPlayerCount,
		C3.Plugins.Photon.Exps.RoomMaxPlayers,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Photon.Cnds.onJoinRoom,
		C3.Plugins.Photon.Acts.setMyRoomMaxPlayers,
		C3.Plugins.Photon.Exps.StateString,
		C3.Plugins.Photon.Exps.MyRoomName,
		C3.Plugins.Photon.Acts.setMyRoomIsOpen
	];
};
self.C3_JsPropNameTable = [
	{mining: 0},
	{Rotate: 0},
	{pick: 0},
	{mine: 0},
	{mine2: 0},
	{mine3: 0},
	{ground: 0},
	{Anchor: 0},
	{usdt_: 0},
	{Browser: 0},
	{b1: 0},
	{usdtbg: 0},
	{PlatformInfo: 0},
	{mineinfo: 0},
	{Touch: 0},
	{GamePush: 0},
	{Usdt: 0},
	{CavePlatforms: 0},
	{Solid: 0},
	{CavePlatforms2: 0},
	{SquareBlack: 0},
	{settings_icon: 0},
	{carriage_: 0},
	{comingsoon: 0},
	{sword_: 0},
	{uiinfo: 0},
	{mining_: 0},
	{Sprite: 0},
	{Platform: 0},
	{Sprite2: 0},
	{pick2: 0},
	{shop_: 0},
	{coin_icon: 0},
	{coin: 0},
	{balance_icon: 0},
	{balance_text: 0},
	{plus: 0},
	{chest_icon: 0},
	{rw_x2button: 0},
	{LocalStorage: 0},
	{rw_info: 0},
	{adv: 0},
	{create_room: 0},
	{Photon: 0},
	{reload: 0},
	{play: 0},
	{lobby_infos: 0},
	{id_room: 0},
	{photon_roominfo: 0},
	{slot: 0},
	{photonlog: 0},
	{mine_section: 0},
	{manat: 0},
	{click: 0},
	{my_photon_nr: 0},
	{photon_status: 0}
];

self.InstanceType = {
	mining: class extends self.ISpriteInstance {},
	pick: class extends self.ISpriteInstance {},
	mine: class extends self.ISpriteInstance {},
	mine2: class extends self.ISpriteInstance {},
	mine3: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	usdt_: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	b1: class extends self.ISpriteInstance {},
	usdtbg: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	mineinfo: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Usdt: class extends self.ITextInstance {},
	CavePlatforms: class extends self.ISpriteInstance {},
	CavePlatforms2: class extends self.ISpriteInstance {},
	SquareBlack: class extends self.ISpriteInstance {},
	settings_icon: class extends self.ISpriteInstance {},
	carriage_: class extends self.ISpriteInstance {},
	comingsoon: class extends self.ITextInstance {},
	sword_: class extends self.ISpriteInstance {},
	uiinfo: class extends self.ITextInstance {},
	mining_: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	pick2: class extends self.ISpriteInstance {},
	shop_: class extends self.ISpriteInstance {},
	coin_icon: class extends self.ISpriteInstance {},
	coin: class extends self.ITextInstance {},
	balance_icon: class extends self.ISpriteInstance {},
	balance_text: class extends self.ITextInstance {},
	plus: class extends self.ISpriteInstance {},
	chest_icon: class extends self.ISpriteInstance {},
	rw_x2button: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	rw_info: class extends self.ITextInstance {},
	adv: class extends self.ISpriteInstance {},
	create_room: class extends self.ISpriteInstance {},
	Photon: class extends self.IInstance {},
	reload: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	lobby_infos: class extends self.ITextInstance {},
	photon_roominfo: class extends self.ITextInstance {},
	slot: class extends self.ISpriteInstance {},
	photonlog: class extends self.ITextInstance {}
}