const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.solid,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Platform,
		C3.Plugins.Arr,
		C3.Plugins.Clipboard,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.EMI_INDO_LogMessage,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Dictionary,
		C3.Plugins.Particles,
		C3.Plugins.HTMLElement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Browser.Acts.SetWindowSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.EMI_INDO_LogMessage.Acts.logMessage,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.JavaScriptInEvents.Main_Event2_Act3,
		C3.JavaScriptInEvents.Main_Event3_Act1,
		C3.Plugins.System.Cnds.Compare,
		C3.JavaScriptInEvents.Main_Event4_Act1,
		C3.Plugins.GamePush_Channels.Acts.SendFeedMessage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsIsPurchased,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchScoped,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.LeaderboardEachPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerIndex,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerPosition,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerField,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.GamePush_Channels.Acts.FetchChannels,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.GamePush_Channels.Cnds.EachChannel,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.GamePush_Channels.Exps.CurChannelID,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.GamePush_Channels.Acts.CreateChannel,
		C3.Plugins.GamePush_Channels.Cnds.IsLastActionSuccess,
		C3.Plugins.GamePush_Channels.Acts.Join,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.GamePush_Channels.Acts.FetchMembers,
		C3.Plugins.GamePush_Channels.Cnds.EachMember,
		C3.Plugins.GamePush_Channels.Exps.CurPlayerID,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.GamePush_Channels.Exps.CurPlayerGet,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.GamePush_Channels.Exps.CurPlayerName,
		C3.Plugins.GamePush_Channels.Exps.CurPlayerAvatar,
		C3.Plugins.GamePush_Channels.Cnds.OnEventJoin,
		C3.JavaScriptInEvents.Referral_Event2_Act1,
		C3.Plugins.GamePush_Channels.Acts.FetchFeedMessages,
		C3.Plugins.GamePush_Channels.Cnds.OnFeedMessagesFetch,
		C3.Plugins.GamePush_Channels.Cnds.EachMessage,
		C3.Plugins.GamePush_Channels.Acts.DeleteMessage,
		C3.Plugins.GamePush_Channels.Exps.CurMessageID
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{mining: 0},
	{Rotate: 0},
	{pick: 0},
	{ground: 0},
	{Anchor: 0},
	{usdt_: 0},
	{Browser: 0},
	{b1: 0},
	{usdtbg: 0},
	{PlatformInfo: 0},
	{mineinfo: 0},
	{Touch: 0},
	{GamePush: 0},
	{Usdt: 0},
	{Solid: 0},
	{digging_platform: 0},
	{settingsuiSquareBlack: 0},
	{settings_icon: 0},
	{mining_icon: 0},
	{comingsoon: 0},
	{pvp_icon: 0},
	{uiinfo: 0},
	{main_icon: 0},
	{Sprite: 0},
	{pick2: 0},
	{shop_: 0},
	{coin_icon: 0},
	{coin: 0},
	{chest_icon: 0},
	{rw_x2button: 0},
	{LocalStorage: 0},
	{rw_info: 0},
	{adv_icon: 0},
	{id_room: 0},
	{slot: 0},
	{my_hero: 0},
	{id_hero: 0},
	{Platform: 0},
	{flapster: 0},
	{Leaders_text: 0},
	{Leaders: 0},
	{wallet_: 0},
	{autoflash_: 0},
	{items: 0},
	{ironpickaxe_shopitem: 0},
	{goldpickaxe_shopitem: 0},
	{crimsonpickaxe_shopitem: 0},
	{emeraldpickaxe_shopitem: 0},
	{energy_bg: 0},
	{tag: 0},
	{InitialWidth: 0},
	{energy_bar: 0},
	{energy_text: 0},
	{user_id: 0},
	{settingsui: 0},
	{walletsui: 0},
	{settingstext: 0},
	{settingsuiexit: 0},
	{Clipboard: 0},
	{copybutton: 0},
	{shopbutton1: 0},
	{shopbutton2: 0},
	{shopbutton3: 0},
	{shopbutton4: 0},
	{shopbuttontext1: 0},
	{shopbuttontext2: 0},
	{shopbuttontext3: 0},
	{shopbuttontext4: 0},
	{loading_bg: 0},
	{coin_item1: 0},
	{coin_item2: 0},
	{coin_item3: 0},
	{Sine2: 0},
	{loading_bar: 0},
	{walletui: 0},
	{settingui2: 0},
	{walletuiexit: 0},
	{walletuiSquareBlack: 0},
	{walletuitext: 0},
	{connectusbutton: 0},
	{connectustext: 0},
	{walletmintext: 0},
	{b2: 0},
	{mineinfo2: 0},
	{mineinfo3: 0},
	{PrevY: 0},
	{CurY: 0},
	{DiffY: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{scroll: 0},
	{LogMessage: 0},
	{diamondpickaxe_shopitem: 0},
	{uishopbg: 0},
	{nav_market: 0},
	{navshop_info: 0},
	{nav_market2: 0},
	{nav_market3: 0},
	{tg_star: 0},
	{shopbutton5: 0},
	{shopbuttontext5: 0},
	{uicoin: 0},
	{uicoin2: 0},
	{add_: 0},
	{trophy_: 0},
	{file_: 0},
	{taskexit: 0},
	{player_avatar: 0},
	{Username: 0},
	{uicoin3: 0},
	{Leaderstext: 0},
	{userleaderboard: 0},
	{autolobbytext: 0},
	{Array: 0},
	{GamePushChannels: 0},
	{Enemy: 0},
	{uiinfo_task: 0},
	{uiinfo_market: 0},
	{uiinfo_home: 0},
	{uiinfo_pvp: 0},
	{uiinfo_mining: 0},
	{prtcofplatform: 0},
	{bgleaders: 0},
	{leaderboardbg: 0},
	{leadersbg2: 0},
	{leadersbg3: 0},
	{leaderboardbg2: 0},
	{leaderboardbg3: 0},
	{leaderboardbg4: 0},
	{top1icon: 0},
	{top2icon: 0},
	{top3icon: 0},
	{leaderboardinfo: 0},
	{leaderboardshineeffect: 0},
	{bgmine: 0},
	{bgleaders2: 0},
	{taskbar_1: 0},
	{task1_text: 0},
	{taskbar_1button: 0},
	{bgleaders3: 0},
	{bgleaders4: 0},
	{task1_text2: 0},
	{task1_coin: 0},
	{task2_coin: 0},
	{taskbar_2button: 0},
	{task2_text2: 0},
	{task2_text: 0},
	{users_: 0},
	{uiinfo_referral: 0},
	{Referral_text: 0},
	{textbox_reflink: 0},
	{textbox_invite: 0},
	{textbox3: 0},
	{Referrallink_text: 0},
	{referralcount_text: 0},
	{HTMLElement: 0},
	{referralinfoincometext: 0},
	{earnedfromreferrals: 0},
	{mine_section: 0},
	{click: 0},
	{x2_timer: 0},
	{coin_backendtime: 0},
	{coin_backend: 0},
	{Referral_level1: 0},
	{Referral_level2: 0},
	{Referral_level3: 0},
	{check_if_registered: 0},
	{item1_bought: 0},
	{item2_bought: 0},
	{item3_bought: 0},
	{item4_bought: 0},
	{item5_bought: 0},
	{Selected: 0},
	{task1_status: 0},
	{task2_status: 0},
	{isRealPvP: 0},
	{isHost: 0},
	{PvPChannelId: 0},
	{ChannelId: 0},
	{player_id: 0},
	{ref_link: 0},
	{parent_candidate: 0},
	{plyid: 0},
	{referral_earnusdt: 0}
];

self.InstanceType = {
	mining: class extends self.ISpriteInstance {},
	pick: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	usdt_: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	b1: class extends self.ISpriteInstance {},
	usdtbg: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	mineinfo: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Usdt: class extends self.ITextInstance {},
	digging_platform: class extends self.ISpriteInstance {},
	settingsuiSquareBlack: class extends self.ISpriteInstance {},
	settings_icon: class extends self.ISpriteInstance {},
	mining_icon: class extends self.ISpriteInstance {},
	comingsoon: class extends self.ITextInstance {},
	pvp_icon: class extends self.ISpriteInstance {},
	uiinfo: class extends self.ITextInstance {},
	main_icon: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pick2: class extends self.ISpriteInstance {},
	shop_: class extends self.ISpriteInstance {},
	coin_icon: class extends self.ISpriteInstance {},
	coin: class extends self.ITextInstance {},
	chest_icon: class extends self.ISpriteInstance {},
	rw_x2button: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	rw_info: class extends self.ITextInstance {},
	adv_icon: class extends self.ISpriteInstance {},
	slot: class extends self.ISpriteInstance {},
	flapster: class extends self.ISpriteInstance {},
	Leaders_text: class extends self.ITextInstance {},
	Leaders: class extends self.IArrayInstance {},
	wallet_: class extends self.ISpriteInstance {},
	autoflash_: class extends self.ISpriteInstance {},
	items: class extends self.ISpriteInstance {},
	ironpickaxe_shopitem: class extends self.ISpriteInstance {},
	goldpickaxe_shopitem: class extends self.ISpriteInstance {},
	crimsonpickaxe_shopitem: class extends self.ISpriteInstance {},
	emeraldpickaxe_shopitem: class extends self.ISpriteInstance {},
	energy_bg: class extends self.ISpriteInstance {},
	energy_bar: class extends self.ISpriteInstance {},
	energy_text: class extends self.ITextInstance {},
	user_id: class extends self.ITextInstance {},
	settingsui: class extends self.ISpriteInstance {},
	walletsui: class extends self.ISpriteInstance {},
	settingstext: class extends self.ITextInstance {},
	settingsuiexit: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	copybutton: class extends self.ISpriteInstance {},
	shopbutton1: class extends self.ISpriteInstance {},
	shopbutton2: class extends self.ISpriteInstance {},
	shopbutton3: class extends self.ISpriteInstance {},
	shopbutton4: class extends self.ISpriteInstance {},
	shopbuttontext1: class extends self.ITextInstance {},
	shopbuttontext2: class extends self.ITextInstance {},
	shopbuttontext3: class extends self.ITextInstance {},
	shopbuttontext4: class extends self.ITextInstance {},
	loading_bg: class extends self.ISpriteInstance {},
	coin_item1: class extends self.ISpriteInstance {},
	coin_item2: class extends self.ISpriteInstance {},
	coin_item3: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ISpriteInstance {},
	walletui: class extends self.ISpriteInstance {},
	settingui2: class extends self.ISpriteInstance {},
	walletuiexit: class extends self.ISpriteInstance {},
	walletuiSquareBlack: class extends self.ISpriteInstance {},
	walletuitext: class extends self.ITextInstance {},
	connectusbutton: class extends self.ISpriteInstance {},
	connectustext: class extends self.ITextInstance {},
	walletmintext: class extends self.ITextInstance {},
	b2: class extends self.ISpriteInstance {},
	mineinfo2: class extends self.ITextInstance {},
	mineinfo3: class extends self.ITextInstance {},
	scroll: class extends self.ISpriteInstance {},
	LogMessage: class extends C3.Plugins.EMI_INDO_LogMessage.Instance {},
	diamondpickaxe_shopitem: class extends self.ISpriteInstance {},
	uishopbg: class extends self.ISpriteInstance {},
	nav_market: class extends self.ISpriteInstance {},
	navshop_info: class extends self.ITextInstance {},
	nav_market2: class extends self.ISpriteInstance {},
	nav_market3: class extends self.ISpriteInstance {},
	tg_star: class extends self.ISpriteInstance {},
	shopbutton5: class extends self.ISpriteInstance {},
	shopbuttontext5: class extends self.ITextInstance {},
	uicoin: class extends self.ISpriteInstance {},
	uicoin2: class extends self.ISpriteInstance {},
	add_: class extends self.ISpriteInstance {},
	trophy_: class extends self.ISpriteInstance {},
	file_: class extends self.ISpriteInstance {},
	taskexit: class extends self.ISpriteInstance {},
	player_avatar: class extends self.ISpriteInstance {},
	Username: class extends self.ITextInstance {},
	uicoin3: class extends self.ISpriteInstance {},
	Leaderstext: class extends self.ITextInstance {},
	userleaderboard: class extends self.ISpriteInstance {},
	autolobbytext: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	GamePushChannels: class extends C3.Plugins.GamePush_Channels.Instance {},
	Enemy: class extends self.IDictionaryInstance {},
	uiinfo_task: class extends self.ITextInstance {},
	uiinfo_market: class extends self.ITextInstance {},
	uiinfo_home: class extends self.ITextInstance {},
	uiinfo_pvp: class extends self.ITextInstance {},
	uiinfo_mining: class extends self.ITextInstance {},
	prtcofplatform: class extends self.IParticlesInstance {},
	bgleaders: class extends self.ISpriteInstance {},
	leaderboardbg: class extends self.ISpriteInstance {},
	leadersbg2: class extends self.ISpriteInstance {},
	leadersbg3: class extends self.ISpriteInstance {},
	leaderboardbg2: class extends self.ISpriteInstance {},
	leaderboardbg3: class extends self.ISpriteInstance {},
	leaderboardbg4: class extends self.ISpriteInstance {},
	top1icon: class extends self.ISpriteInstance {},
	top2icon: class extends self.ISpriteInstance {},
	top3icon: class extends self.ISpriteInstance {},
	leaderboardinfo: class extends self.ISpriteInstance {},
	leaderboardshineeffect: class extends self.ISpriteInstance {},
	bgmine: class extends self.ISpriteInstance {},
	bgleaders2: class extends self.ISpriteInstance {},
	taskbar_1: class extends self.ISpriteInstance {},
	task1_text: class extends self.ITextInstance {},
	taskbar_1button: class extends self.ISpriteInstance {},
	bgleaders3: class extends self.ISpriteInstance {},
	bgleaders4: class extends self.ISpriteInstance {},
	task1_text2: class extends self.ITextInstance {},
	task1_coin: class extends self.ISpriteInstance {},
	task2_coin: class extends self.ISpriteInstance {},
	taskbar_2button: class extends self.ISpriteInstance {},
	task2_text2: class extends self.ITextInstance {},
	task2_text: class extends self.ITextInstance {},
	users_: class extends self.ISpriteInstance {},
	uiinfo_referral: class extends self.ITextInstance {},
	Referral_text: class extends self.ITextInstance {},
	textbox_reflink: class extends self.ISpriteInstance {},
	textbox_invite: class extends self.ISpriteInstance {},
	textbox3: class extends self.ISpriteInstance {},
	Referrallink_text: class extends self.ITextInstance {},
	referralcount_text: class extends self.ITextInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	referralinfoincometext: class extends self.ITextInstance {},
	earnedfromreferrals: class extends self.ITextInstance {}
}